In [2]:
import numpy as np
from mayavi import mlab
from pathlib import Path
import scipy

In [3]:
import scipy
from scipy.spatial.transform import Rotation
#设置print精度

#平移变换
def translation(qx,qy,qz):
    Dq = np.array([[1,0,0,qx],
                 [0,1,0,qy],
                 [0,0,1,qz],
                 [0,0,0,1]],dtype=float)
    return Dq
#旋转变换npa
def rotation(cls,angles):
    r = Rotation.from_euler(cls,angles,degrees=True)
    R = r.as_matrix()
    return R
#一般变换
def transform(Dm,Rm):
    if(Dm.shape !=(4,4) or Rm.shape!=(3,3)):
        raise IndexError("Wrong Matrix size!")
    temp = np.append(Rm,np.reshape(Dm[:3,3],(3,1)),axis=1)
    temp = np.append(temp,[[0.,0.,0.,1.]],axis=0)
    return temp
#DH变换
def DH_transform(alpha,a,d,theta):
    ScrewX = transform(translation(a,0,0),rotation('x',alpha))
    ScrewZ =transform(translation(0,0,d),rotation('z',theta))
    T = ScrewX @ ScrewZ
    return T


In [4]:
#假设舵机角度
a0 =-45
a1 = -60
a2 = -120
a3 = -90
a4 = 0
D0 = translation(0,0,0)
R0 = rotation('xyz',[0,a0,0])
T0 = transform(D0,R0)
T1 = DH_transform(0,0,0,a1)
T2 = DH_transform(180,100,0,a2)
T3 = DH_transform(180,100,0,a3)
T4 = DH_transform(90,0,10,a4)

In [16]:
print(T0)
print(T1)
print(rotation('xyz',[0,90,0]))
m =np.array([[1,0,0],
             [0,-1,0],
             [0,0,-1]])
r = Rotation.from_euler('z',-np.pi)

print(r.as_matrix() )
#print(np.reshape(D[:3,3],(3,1)))

[[ 0.70710678 -0.         -0.70710678  0.        ]
 [ 0.          1.         -0.          0.        ]
 [ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.          0.          1.        ]]
[[ 0.5        0.8660254  0.         0.       ]
 [-0.8660254  0.5        0.         0.       ]
 [ 0.         0.         1.         0.       ]
 [ 0.         0.         0.         1.       ]]
[[ 2.22044605e-16  0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-1.00000000e+00  0.00000000e+00  2.22044605e-16]]
[[-1.0000000e+00  1.2246468e-16  0.0000000e+00]
 [-1.2246468e-16 -1.0000000e+00 -0.0000000e+00]
 [-0.0000000e+00  0.0000000e+00  1.0000000e+00]]


In [4]:
#打印一个4*4位姿
def mlab_showApose(pose):
    mlab.quiver3d(pose[0][3], pose[1][3], pose[2][3], pose[0][0], pose[1][0], pose[2][0], line_width=2, scale_factor=80, colormap = "Reds")
    mlab.quiver3d(pose[0][3], pose[1][3], pose[2][3], pose[0][1], pose[1][1], pose[2][1], line_width=2, scale_factor=80, colormap = "Greens")
    mlab.quiver3d(pose[0][3], pose[1][3], pose[2][3], pose[0][2], pose[1][2], pose[2][2], line_width=2, scale_factor=100, colormap = "Blues")

In [5]:

mlab.quiver3d(0, 0, 0, 1, 0, 0, line_width=4, scale_factor=200, colormap = "Reds")
mlab.quiver3d(0, 0, 0, 0, 1, 0, line_width=4, scale_factor=200, colormap = "Greens")
mlab.quiver3d(0, 0, 0, 0, 0, 1, line_width=4, scale_factor=200, colormap = "Blues")
mlab_showApose(T0)
mlab_showApose(T0@T1)
mlab_showApose(T0@T1@T2)
mlab_showApose(T0@T1@T2@T3)
mlab_showApose(T0@T1@T2@T3@T4)
mlab.show()

In [6]:
import sympy as sy
a1,a2,a3,a4,l1,l2,l3,l4,d1,d2,d3,d4,t1 =sy.symbols('a1,a2,a3,a4,l1,l2,l3,l4,d1,d2,d3,d4,t1', real =True)
D0 = translation(0,0,0)
R0 = rotation('xyz',[0,-45,0])
def DH_T(alpha, a, d, theta):
    m = sy.Matrix([[sy.cos(theta), -sy.sin(theta), 0, a],
                [sy.sin(theta)*sy.cos(alpha), sy.cos(theta)*sy.cos(alpha), -sy.sin(alpha), -sy.sin(alpha)*d],
                [sy.sin(theta)*sy.sin(alpha), sy.cos(theta)*sy.sin(alpha), sy.cos(alpha), sy.cos(alpha)*d],
                [0, 0, 0, 1]])
    return m
def
#DH_T(0,0,0,a1)*DH_T(0,l1,0,a2)*DH_T(0,l2,0,a3)


In [7]:
#solve h/cos(a0)=l1*cos(a1)+l2*sin(-a2+a1-pi/2),l1*sin(a1)=x+l2*cos(-a2+a1-pi/2),a3=a1-a2-pi/2,a0=pi/6 for a1,a2,a3

In [9]:
DH_T(t1,l1,d1,a1)

Matrix([
[        cos(a1),        -sin(a1),        0,          l1],
[sin(a1)*cos(t1), cos(a1)*cos(t1), -sin(t1), -d1*sin(t1)],
[sin(a1)*sin(t1), sin(t1)*cos(a1),  cos(t1),  d1*cos(t1)],
[              0,               0,        0,           1]])

In [6]:
DH_T(0,l1,0,a2)

Matrix([
[cos(a2), -sin(a2), 0, l1],
[sin(a2),  cos(a2), 0,  0],
[      0,        0, 1,  0],
[      0,        0, 0,  1]])

In [7]:
DH_T(0,l2,0,a3)

Matrix([
[cos(a3), -sin(a3), 0, l2],
[sin(a3),  cos(a3), 0,  0],
[      0,        0, 1,  0],
[      0,        0, 0,  1]])